name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  postgres-14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '14.1'
        tags: 14.1,14,latest
        workdir: 14
        platform: linux/amd64,linux/arm64
  postgres-13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '13.5'
        tags: 13.5,13
        workdir: 13
        platform: linux/amd64,linux/arm64
  postgres-12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '12.9'
        tags: 12.9,12
        workdir: 12
        platform: linux/amd64,linux/arm64
  postgres-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '11.14'
        tags: 11.14,11
        workdir: 11
        platform: linux/amd64,linux/arm64
  postgres-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '10.19'
        tags: 10.19,10
        workdir: 10
        platform: linux/amd64,linux/arm64
  postgres-96:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '9.6.24'
        tags: 9.6.24,9.6,9
        workdir: 9.6
        platform: linux/amd64,linux/arm64

